# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [84]:
import numpy as np

#### Create an array of 10 zeros 

In [85]:
arr0 = np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [86]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [87]:
arr5 = 5*arr1
arr5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [88]:
arr_1050 = np.arange(10,51)
arr_1050

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [89]:
arr_1050_even = np.arange(10,51,2)
arr_1050_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [90]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [91]:
Iden_matrix = np.identity(3)
Iden_matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [92]:
import random

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [93]:
ran_arr = np.random.randn(25)
ran_arr

array([-1.94680213, -1.7714686 , -0.55830471,  0.75181777, -0.05320035,
        0.72848086,  0.53000767,  0.47224111, -0.6376969 ,  1.13669804,
       -0.16002742,  0.63027184,  0.32454991, -0.8764925 , -0.07261068,
        0.46195953,  0.22114586, -1.72452446, -0.29207717, -0.19148747,
        0.20992823,  0.00706551, -1.19996757, -1.63221072,  0.89478886])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [94]:
array = np.linspace(0,1,20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [95]:
array = np.linspace(0,1,20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Import pandas as pd.**

In [96]:
import pandas as pd


**Read Salaries.csv as a dataframe called sal.**

In [97]:
sal = pd.read_csv('Salaries.csv')


/var/folders/g8/5t4b076s6_g5q607z28syb7c0000gn/T/ipykernel_56798/738420081.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('Salaries.csv')


**Check the head of the DataFrame.**

In [98]:
sal.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

**Use the .info() method to find out how many entries there are.**

In [99]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


**What is the average BasePay ?**

In [100]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')

avg_basepay_per_year = sal[sal['Year'].between(2011, 2014)].groupby('Year')['BasePay'].mean()

print(avg_basepay_per_year)


Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64


**What is the highest amount of OvertimePay in the dataset ?**

In [101]:
highest_OvertimePay = pd.to_numeric(sal['OvertimePay'], errors='coerce').max()
highest_OvertimePay

245131.88

**What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).**

In [102]:
job_title = sal.query('EmployeeName == "JOSEPH DRISCOLL"')['JobTitle'].iloc[0]
job_title

'CAPTAIN, FIRE SUPPRESSION'

**How much does JOSEPH DRISCOLL make (including benefits)?**

In [103]:
total_pay_benefits = sal.query('EmployeeName == "JOSEPH DRISCOLL"')['TotalPayBenefits'].iloc[0]
total_pay_benefits

270324.91

**What is the name of highest paid person (including benefits)?**

In [104]:
highest_tot_pay_benefit = sal['TotalPayBenefits'].max()
highest_paid_person = sal.query(f'TotalPayBenefits == {highest_tot_pay_benefit}')['EmployeeName'].iloc[0]
highest_paid_person

'NATHANIEL FORD'

**What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [105]:
lowest_tot_pay_benefit = sal['TotalPayBenefits'].min()
lowest_paid_person = sal.query(f'TotalPayBenefits == {lowest_tot_pay_benefit}')['EmployeeName'].iloc[0]
lowest_paid_person

'Joe Lopez'

**What was the average (mean) BasePay of all employees per year? (2011-2014)?**

In [106]:

sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')

avg_basepay_per_year = sal[sal['Year'].between(2011, 2014)].groupby('Year')['BasePay'].mean()

print(avg_basepay_per_year)


Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64


**How many unique job titles are there?**

In [107]:
num_unique_jobTitle = len(sal['JobTitle'].unique())
num_unique_jobTitle


2159

**What are the top 5 most common jobs?**

In [108]:
top_jobs = sal['JobTitle'].value_counts().head(5)
top_jobs

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

**What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [109]:
lowest_tot_pay_benefit = sal['TotalPayBenefits'].min()
lowest_paid_person = sal.query(f'TotalPayBenefits == {lowest_tot_pay_benefit}')['EmployeeName'].iloc[0]
lowest_paid_person

'Joe Lopez'

# Great Job!